Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('main.c')

if GetDepend(['APP_USING_ADC_APP']):
    src += Glob('APP/Src/adc_app.c')

if GetDepend(['APP_USING_IN_FLASH_APP']):
    src += Glob('APP/Src/In_Flash_app.c')

if GetDepend(['APP_USING_PICOCAP_APP']):
    src += Glob('APP/Src/Picocap_app.c')

if GetDepend(['APP_USING_USART_APP']):
    src += Glob('APP/Src/usart_app.c')

if GetDepend(['APP_USING_MODBUS']):
	src += Split('''
				APP/Src/ModBusRTU.c
				APP/Src/ModBus_Conf.c
				APP/Src/TypeConvert.c
				''')

path =  [cwd]
path += [cwd + '/APP/Inc']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
