import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32f0xx_hal_msp.c
''')

if GetDepend(['BSP_USING_ADC_BSP']):
    src += Glob('BSP/Src/adc_bsp.c')

if GetDepend(['BSP_USING_DAC_BSP']):
    src += Glob('BSP/Src/dac_bsp.c')

if GetDepend(['BSP_USING_IN_FLASH']):
    src += Glob('BSP/Src/In_Flash.c')

if GetDepend(['BSP_USING_PICOCAP']):
	src += Glob('BSP/Src/Picocap.c')

if GetDepend(['BSP_SPI_BSP']):
	src += Glob('BSP/Src/spi_bsp.c')

if GetDepend(['BSP_USING_USART_BSP']):
    src += Glob('BSP/Src/usart_bsp.c')

path =  [cwd]
path += [cwd + '/ports']
path += [cwd + '/CubeMX_Config/Inc']
path += [cwd + '/BSP/Inc']

startup_path_prefix = SDK_LIB

if rtconfig.CROSS_TOOL == 'gcc':
    src += [startup_path_prefix + '/STM32F0xx_HAL/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc/startup_stm32f072xb.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [startup_path_prefix + '/STM32F0xx_HAL/CMSIS/Device/ST/STM32F0xx/Source/Templates/arm/startup_stm32f072xb.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [startup_path_prefix + '/STM32F0xx_HAL/CMSIS/Device/ST/STM32F0xx/Source/Templates/iar/startup_stm32f072xb.s']
    
CPPDEFINES = ['STM32F072xB']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
